import { registerCommon } from "./ovale_common";
import { registerDeathKnightSpells } from "./ovale_deathknight_spells";
import { OvaleScriptsClass } from "../engine/scripts";
import { registerDeathKnight } from "./ovale_deathknight";
import { registerDemonHunter } from "./ovale_demonhunter";
import { registerDruid } from "./ovale_druid";
import { registerHunter } from "./ovale_hunter";
import { registerMage } from "./ovale_mage";
import { registerMonk } from "./ovale_monk";
import { registerPaladin } from "./ovale_paladin";
import { registerPriest } from "./ovale_priest";
import { registerRogue } from "./ovale_rogue";
import { registerShaman } from "./ovale_shaman";
import { registerWarlock } from "./ovale_warlock";
import { registerWarrior } from "./ovale_warrior";
import { registerDemonHunterSpells } from "./ovale_demonhunter_spells";
import { registerDruidSpells } from "./ovale_druid_spells";
import { registerHunterSpells } from "./ovale_hunter_spells";
import { registerMageSpells } from "./ovale_mage_spells";
import { registerMonkSpells } from "./ovale_monk_spells";
import { registerPaladinSpells } from "./ovale_paladin_spells";
import { registerPriestSpells } from "./ovale_priest_spells";
import { registerRogueSpells } from "./ovale_rogue_spells";
import { registerShamanSpells } from "./ovale_shaman_spells";
import { registerWarlockSpells } from "./ovale_warlock_spells";
import { registerWarriorSpells } from "./ovale_warrior_spells";

export function registerScripts(ovaleScripts: OvaleScriptsClass) {
    registerCommon(ovaleScripts);
    registerDeathKnightSpells(ovaleScripts);
    registerDemonHunterSpells(ovaleScripts);
    registerDruidSpells(ovaleScripts);
    registerHunterSpells(ovaleScripts);
    registerMageSpells(ovaleScripts);
    registerMonkSpells(ovaleScripts);
    registerPaladinSpells(ovaleScripts);
    registerPriestSpells(ovaleScripts);
    registerRogueSpells(ovaleScripts);
    registerShamanSpells(ovaleScripts);
    registerWarlockSpells(ovaleScripts);
    registerWarriorSpells(ovaleScripts);

    registerDeathKnight(ovaleScripts);
    registerDemonHunter(ovaleScripts);
    registerDruid(ovaleScripts);
    registerHunter(ovaleScripts);
    registerMage(ovaleScripts);
    registerMonk(ovaleScripts);
    registerPaladin(ovaleScripts);
    registerPriest(ovaleScripts);
    registerRogue(ovaleScripts);
    registerShaman(ovaleScripts);
    registerWarlock(ovaleScripts);
    registerWarrior(ovaleScripts);
}
