import { OvaleScripts } from "../Scripts";
export function register() {
    let name = "ovale_mage_spells";
    let desc = "[7.0] Ovale: Mage spells";
	let code = `

# Mage spells and functions.
Define(arcane_barrage 44425)
	SpellInfo(arcane_barrage cd=3 travel_time=1 max_arcanecharges=4)
Define(arcane_blast 30451)
	SpellInfo(arcane_blast arcanecharges=-1)
	SpellAddBuff(arcane_blast presence_of_mind_buff=-1)
Define(arcane_explosion 1449)
	SpellInfo(arcane_explosion arcanecharges=-1)
Define(arcane_familiar 205022)
	SpellInfo(arcane_familiar cd=10)
	SpellAddBuff(arcane_familiar arcane_familiar_buff=1)
	SpellRequire(arcane_familiar unusable 1=buff,arcane_familiar_buff)
Define(arcane_familiar_buff 210126)
	SpellInfo(arcane_familiar_buff duration=3600)
Define(arcane_intellect 1459)
	SpellAddBuff(arcane_intellect arcane_intellect_buff=1)
	SpellRequire(arcane_intellect unusable 1=buff,arcane_intellect_buff)
Define(arcane_intellect_buff 1459)
	SpellInfo(arcane_intellect_buff duration=3600)
Define(arcane_missiles 5143)
	SpellInfo(arcane_missiles channel=2.5 travel_time=1)
	SpellAddBuff(arcane_missiles clearcastign_buff=-1)
Define(arcane_orb 153626)
	SpellInfo(arcane_orb cd=20 arcanecharges=-1)
Define(arcane_power 12042)
	SpellInfo(arcane_power cd=90 gcd=0)
	SpellAddBuff(arcane_power arcane_power_buff=1)
Define(arcane_power_buff 12042)
	SpellInfo(arcane_power_buff duration=10)
Define(blast_wave 157981)
	SpellInfo(blast_wave cd=25)
Define(blazing_barrier 235313)
	SpellInfo(blazing_barrier cd=25)
Define(blazing_barrier_buff 235313)
	SpellInfo(blazing_barrier_buff duration=60)
Define(blink 1953)
	SpellInfo(blink cd=15)
	SpellInfo(blink replace=shimmer talent=shimmer_talent)
Define(blizzard 190356)
	SpellInfo(blizzard cd=8 haste=spell)
	SpellAddBuff(blizzard ice_floes_buff=-1 talent=ice_floes_talent)
Define(bone_chilling_buff 205766)
	SpellInfo(bone_chilling_buff duration=8 max_stacks=10)
Define(brain_freeze_buff 190446)
	SpellInfo(brain_freeze_buff duration=15)
Define(chain_reaction_buff 278310)
	SpellInfo(chain_reaction_buff duration=10 max_stacks=5)
Define(charged_up 205032)
	SpellInfo(charged_up cd=40 arcanecharges=-4)
Define(clearcasting_buff 263725)
	SpellInfo(clearcasting_buff duration=15)
Define(cold_snap 235219)
	SpellInfo(cold_snap cd=300 gcd=0 offgcd=1)
Define(combustion 190319)
	SpellInfo(combustion cd=120 gcd=0)
	SpellAddBuff(combustion combustion_buff=1)
Define(combustion_buff 190319)
	SpellInfo(combustion_buff duration=10)
Define(comet_storm 153595)
	SpellInfo(comet_storm cd=30 travel_time=1)
Define(cone_of_cold 120)
	SpellInfo(cone_of_cold cd=12)
Define(counterspell 2139)
	SpellInfo(counterspell cd=24 gcd=0 interrupt=1)
Define(displacement 195676)
	SpellInfo(displacement cd=30)
Define(dragons_breath 31661)
	SpellInfo(dragons_breath cd=20)
Define(ebonbolt 257537)
	SpellInfo(ebonbolt cd=45 tag=main)
	SpellAddBuff(ebonbolt brain_freeze_buff=1)
Define(enhanced_pyrotechnics_buff 157644)
	SpellInfo(enhanced_pyrotechnics_buff duration=15)
Define(evocation 12051)
	SpellInfo(evocation cd=90 channel=6 haste=spell)
Define(fingers_of_frost_buff 44544)
	SpellInfo(fingers_of_frost_buff duration=15 max_stacks=2)
Define(fire_blast 108853)
	SpellInfo(fire_blast gcd=0 offgcd=1 cd=12 ch_haste=spell charges=2)
	SpellInfo(fire_blast cd=10 charges=3 talent=flame_on_talent)
Define(fireball 133)
Define(flamestrike 2120)
	SpellAddTargetDebuff(flamestrike flamestrike_debuff=1)
	SpellAddBuff(flamestrike hot_streak_buff=0)
Define(flamestrike_debuff 2120)
	SpellInfo(flamestrike_debuff duration=8 haste=spell tick=2)
Define(flurry 44614)
	SpellInfo(flurry travel_time=1)
	SpellAddTargetDebuff(flurry winters_chill_debuff=1 if_buff=brain_freeze_buff)
	#SpellAddBuff(flurry brain_freeze_buff=0) # Can't use it with above SpellAddTargetDebuff
Define(freezing_rain_buff 270232)
	SpellInfo(freezing_rain_buff duration=12)
Define(frost_nova 122)
	SpellInfo(frost_nova cd=30)
	SpellInfo(frost_nova charges=2 talent=ice_ward_talent)
Define(frostbolt 116)
	SpellInfo(frostbolt travel_time=1)
	SpellAddBuff(frostbolt icicles_buff=1)
	SpellAddBuff(frostbolt ice_floes_buff=-1 talent=ice_floes_talent)
Define(frozen_orb 84714)
	SpellInfo(frozen_orb cd=60)
	SpellAddBuff(frozen_orb freezing_rain_buff=1 talent=freezing_rain_talent)
Define(glacial_spike 199786)
	SpellInfo(glacial_spike mana=1 unusable=1)
	SpellRequire(glacial_spike unusable 0=buff,icicles_buff,5)
	SpellAddBuff(glacial_spike icicles_buff=0)
	SpellAddBuff(glacial_spike ice_floes_buff=-1 talent=ice_floes_talent)
Define(greater_invisibility 110959)
	SpellInfo(greater_invisibility cd=120)
	SpellAddBuff(greater_invisibility greater_invisibility_buff=1)
Define(greater_invisibility_buff 110960)
	SpellInfo(greater_invisibility_buff duration=20)
Define(heating_up_buff 48107)
	SpellInfo(heating_up_buff duration=10)
Define(hot_streak_buff 48108)
	SpellInfo(hot_streak_buff duration=15)
Define(ice_barrier 11426)
	SpellInfo(ice_barrier cd=25)
Define(ice_barrier_buff 11426)
	SpellInfo(ice_barrier_buff duration=60)
Define(ice_block 45438)
	SpellInfo(ice_block cd=240)
	SpellRequire(ice_block unusable 1=buff,hypotermia_debuff)
	SpellAddBuff(ice_block ice_block_buff=1)
	SpellAddDebuff(ice_block hypotermia_debuff=1)
Define(ice_block_buff 45438)
	SpellInfo(ice_block_buff duration=10)
Define(ice_floes 108839)
	SpellInfo(ice_floes cd=20 charges=3)
Define(ice_floes_buff 108839)
	SpellInfo(ice_floes_buff duration=15 max_stacks=3)
Define(ice_lance 30455)
	SpellInfo(ice_lance travel_time=1.3) # maximum observed travel time with a bit of padding
	SpellAddBuff(ice_lance fingers_of_frost_buff=-1)
	#SpellAddBuff(ice_lance icy_veins_buff=extend,2 if_spell=thermal_void) #TODO
Define(ice_nova 157997)
	SpellInfo(ice_nova cd=25)
	SpellAddTargetDebuff(ice_nova ice_nova_debuff=1)
Define(ice_nova_debuff 157997)
	SpellInfo(ice_nova_debuff duration=2)
Define(icicles_buff 205473)
	SpellInfo(icicles_buff duration=60 max_stacks=5)
Define(icy_veins 12472)
	SpellInfo(icy_veins cd=180)
	SpellAddBuff(icy_veins icy_veins_buff=1)
Define(icy_veins_buff 12472)
	SpellInfo(icy_veins_buff duration=20)
	SpellInfo(icy_veins_buff add_duration=10 talent=thermal_void_talent)
Define(ignite_debuff 12654)
	SpellInfo(ignite_debuff duration=5 tick=1)
Define(incanters_flow_buff 116267)
	SpellInfo(incanters_flow_buff duration=25 max_stacks=5)
Define(invisibility 66)
	SpellInfo(invisibility cd=300)
Define(living_bomb 44457)
	SpellInfo(living_bomb cd=12)
	SpellAddTargetDebuff(living_bomb living_bomb_debuff=1)
Define(living_bomb_debuff 217694)
	SpellInfo(living_bomb_debuff duration=4 tick=1)
Define(lonely_winter 205024)
	SpellInfo(lonely_winter unusable=1)
	SpellInfo(lonely_winter replace=summon_water_elemental talent=lonely_winter_talent)
Define(meteor 153561)
	SpellInfo(meteor cd=45 travel_time=1)
Define(mirror_image 55342)
	SpellInfo(mirror_image cd=120)
Define(nether_tempest 114923)
	SpellAddTargetDebuff(nether_tempest nether_tempest_debuff=1)
Define(nether_tempest_debuff 114923)
	SpellInfo(nether_tempest_debuff duration=12 haste=spell tick=1)
Define(phoenix_flames 257541)
	SpellInfo(phoenixs_flames cd=30 charges=3)
Define(polymorph 118)
	SpellAddTargetDebuff(polymorph polymorph_debuff=1)
Define(polymorph_debuff 118)
	SpellInfo(polymorph_debuff duration=60)
Define(presence_of_mind 205025)
	SpellInfo(presence_of_mind cd=60 gcd=0 offgcd=1)
	SpellAddBuff(presence_of_mind presence_of_mind_buff=1)
Define(presence_of_mind_buff 205025)
	SpellInfo(presence_of_mind_buff stacks=2)
Define(prismatic_barrier 235450)
	SpellInfo(prismatic_barrier cd=25)
	SpellAddBuff(prismatic_barrier prismatic_barrier_buff=1)
Define(prismatic_barrier_buff 235450)
	SpellInfo(prismatic_barrier_buff duration=60)
Define(pyroblast 11366)
	SpellInfo(pyroblast travel_time=1)
	SpellAddBuff(pyroblast hot_streak_buff=0)
	SpellAddBuff(pyroblast pyroclasm_buff=0)
Define(pyroclasm_buff 269651)
	SpellInfo(pyroclasm_buff duration=15)
Define(ray_of_frost 205021)
	SpellInfo(ray_of_frost cd=78 channel=5 tag=main)
Define(remove_curse 475)
	SpellInfo(remove_curse cd=8)
Define(ring_of_frost 113724)
	SpellInfo(ring_of_frost cd=45)
Define(rune_of_power 116011)
	SpellInfo(rune_of_power buff_totem=rune_of_power_buff duration=10 max_totems=2 totem=1)
	SpellAddBuff(rune_of_power ice_floes_buff=-1 specialization=frost)
Define(rule_of_threes_buff 264774)
	SpellInfo(rule_of_threes_buff duration=15)
Define(rune_of_power_buff 116014)
Define(scorch 2948)
	SpellInfo(scorch travel_time=1)
Define(shimmer 212653)
	SpellInfo(shimmer cd=20 charges=2)
	SpellInfo(shimmer replace=blink talent=!shimmer_talent)
Define(slow 31589)
Define(slow_fall 130)
Define(spellsteal 30449)
Define(summon_water_elemental 31687)
	SpellInfo(summon_water_elemental cd=30)
	SpellInfo(summon_water_elemental unusable=1 talent=lonely_winter_talent)
Define(supernova 157980)
	SpellInfo(supernova cd=25)
Define(temporal_displacement_debuff 80354)
	SpellInfo(temporal_displacement_debuff duration=600)
Define(time_warp 80353)
	SpellInfo(time_warp cd=300 gcd=0)
	SpellAddBuff(time_warp time_warp_buff=1)
	SpellAddDebuff(time_warp temporal_displacement_debuff=1 if_equipped=!shard_of_the_exodar_item)
Define(time_warp_buff 80353)
	SpellInfo(time_warp_buff duration=40)
Define(winters_chill_debuff 228358)
	SpellInfo(winters_chill_debuff duration=3)

# Pet Abilities
Define(pet_freeze 33395)
	SpellInfo(pet_freeze cd=25)

# Azerite Traits
Define(winters_reach_trait 273346) 
	Define(winters_reach_buff 273346)
		SpellInfo(winters_reach_buff duration=15)
Define(arcane_pressure_trait 274594)

# Legendary items
Define(lady_vashjs_grasp 132411)
Define(rhonins_assaulting_armwraps_buff 208081)
Define(shard_of_the_exodar 132410)
Define(zannesu_journey_buff 226852)
	SpellAddBuff(blizzard zannesu_journey_buff=-1)
Define(koralons_burning_touch_item 132454)
Define(darcklis_dragonfire_diadem_item 132863)
Define(erupting_infernal_core_buff 248147)
	SpellInfo(erupting_infernal_core_buff duration=30)
Define(marquee_bindings_of_the_sun_king_item 132406)
	Define(kaelthas_ultimate_ability_buff 209455)
		SpellInfo(kaelthas_ultimate_ability_buff duration=15)
Define(shard_of_the_exodar_item 132410)
	Define(shard_of_the_exodar_warp 207970)
Define(gravity_spiral_item 144274)
Define(mystic_kilt_of_the_rune_master_item 132451)


# Talents
Define(alexstraszas_fury_talent 11)
Define(amplification_talent 1)
Define(arcane_familiar_talent 3)
Define(arcane_orb_talent 21)
Define(blast_wave_talent 6)
Define(blazing_soul_talent 4)
Define(bone_chilling_talent 1)
Define(chain_reaction_talent 11)
Define(charged_up_talent 11)
Define(chrono_shift_talent 13)
Define(comet_storm_talent 18)
Define(conflagration_talent 17)
Define(ebonbolt_talent 12)
Define(firestarter_talent 1)
Define(flame_on_talent 10)
Define(flame_patch_talent 16)
Define(freezing_rain_talent 16)
Define(frenetic_speed_talent 13)
Define(frigid_winds_talent 13)
Define(frozen_touch_talent 10)
Define(glacial_insulation_talent 4)
Define(glacial_spike_talent 21)
Define(ice_floes_talent 6)
Define(ice_nova_talent 3)
Define(ice_ward_talent 14)
Define(incanters_flow_talent 7)
Define(kindling_talent 19)
Define(living_bomb_talent 18)
Define(lonely_winter_talent 2)
Define(mana_shield_talent 4)
Define(meteor_talent 21)
Define(mirror_image_talent 8)
Define(nether_tempest_talent 18)
Define(overpowered_talent 19)
Define(phoenix_flames_talent 12)
Define(pyroclasm_talent 20)
Define(pyromaniac_talent 2)
Define(ray_of_frost_talent 20)
Define(resonance_talent 10)
Define(reverberate_talent 16)
Define(ring_of_frost_talent 15)
Define(rule_of_threes_talent 2)
Define(rune_of_power_talent 9)
Define(searing_touch_talent 3)
Define(shimmer_talent 5)
Define(slipstream_talent 6)
Define(splitting_ice_talent 17)
Define(supernova_talent 12)
Define(thermal_void_talent 19)
Define(time_anomaly_talent 20)
Define(touch_of_the_magi_talent 17)
	
# Non-default tags for OvaleSimulationCraft.
	SpellInfo(arcane_orb tag=shortcd)
	SpellInfo(arcane_power tag=cd)
	SpellInfo(blink tag=shortcd)
	SpellInfo(cone_of_cold tag=shortcd)
	SpellInfo(dragons_breath tag=shortcd)
	SpellInfo(frost_bomb tag=shortcd)
	SpellInfo(ice_floes tag=shortcd)
	SpellInfo(rune_of_power tag=shortcd)
	SpellInfo(evocation tag=main)

`;
    OvaleScripts.RegisterScript("MAGE", undefined, name, desc, code, "include");
}
