local OVALE, Ovale = ...
local OvaleScripts = Ovale.OvaleScripts

do
	local name = "ovale_hunter_spells"
	local desc = "[7.0] Ovale: Hunter spells"
	local code = [[
# Hunter spells and functions.

Define(a_murder_of_crows 131894)
	SpellInfo(a_murder_of_crows cd=60 focus=30)
	SpellInfo(a_murder_of_crows buff_focus_half=bestial_wrath_buff if_spell=bestial_wrath)
Define(a_murder_of_crows_talent 13)
Define(aimed_shot 19434)
	SpellInfo(aimed_shot focus=50)
	SpellInfo(aimed_shot buff_focus=thrill_of_the_hunt_buff buff_focus_amount=-20 if_spell=thrill_of_the_hunt)
	SpellAddBuff(aimed_shot thrill_of_the_hunt_buff=-1 if_spell=thrill_of_the_hunt)
Define(arcane_shot 185358)
	SpellInfo(arcane_shot focus=30)
	SpellInfo(arcane_shot buff_focus=thrill_of_the_hunt_buff buff_focus_amount=-20 if_spell=thrill_of_the_hunt)
	SpellInfo(arcane_shot buff_focus_half=bestial_wrath_buff if_spell=bestial_wrath)
	SpellAddBuff(arcane_shot thrill_of_the_hunt_buff=-1 if_spell=thrill_of_the_hunt)
	SpellAddBuff(arcane_shot focus_fire_buff=extend,1 itemset=T18 itemcount=2 specialization=beast_mastery)
	SpellAddTargetDebuff(arcane_shot serpent_sting_debuff=1 if_spell=serpent_sting)
Define(aspect_of_the_eagle 186289)
	SpellInfo(aspect_of_the_eagle cd=120)
	SpellAddBuff(aspect_of_the_eagle aspect_of_the_eagle_buff=1)
Define(aspect_of_the_eagle_buff 186289)
	SpellInfo(aspect_of_the_eagle_buff duration=10)
Define(aspect_of_the_wild 193530)
	SpellInfo(aspect_of_the_wild cd=120)
Define(aspect_of_the_wild_buff 193530)
	SpellInfo(aspect_of_the_wild_buff duration=10)
Define(barrage 120360)
	SpellInfo(barrage cd=20 focus=60)
	SpellInfo(barrage buff_focus_half=bestial_wrath_buff if_spell=bestial_wrath)
Define(bestial_wrath 19574)
	SpellInfo(bestial_wrath cd=60 gcd=0)
	SpellInfo(bestial_wrath buff_cdr=cooldown_reduction_agility_buff)
	SpellAddBuff(bestial_wrath bestial_wrath_buff=1)
Define(bestial_wrath_buff 19574)
	SpellInfo(bestial_wrath_buff duration=15)
Define(black_arrow 194599)
	SpellInfo(black_arrow cd=24 focus=35)
	SpellInfo(black_arrow buff_cdr=cooldown_reduction_agility_buff)
	SpellAddBuff(black_arrow lock_and_load_buff=2 itemset=T17 itemcount=2 specialization=aaaaaaaaaaasurvival)
	SpellAddTargetDebuff(black_arrow black_arrow_debuff=1)
	SpellAddTargetDebuff(black_arrow black_decay_debuff=1 itemset=T18 itemcount=2 specialization=survival)
Define(black_arrow_debuff 194599)
	SpellInfo(black_arrow_debuff duration=20 tick=2)
Define(bullseye 204089)
Define(bullseye_buff 204089)
Define(butchery 212436)
	SpellInfo(butchery focus=40 cd=15)
Define(careful_aim_talent 3)
Define(carve 187708)
	SpellInfo(carve focus=40)
	SpellAddTargetDebuff(carve serpent_sting_debuff=1 talent=serpent_sting_talent)
Define(chimaera_shot 53209)
	SpellInfo(chimaera_shot cd=9 focus=35)
Define(cobra_shot 193455)
	SpellInfo(cobra_shot focus=-14)
Define(dire_beast 120679)
	SpellInfo(dire_beast cd=30)
Define(dire_beast_buff 120679)
	SpellInfo(dire_beast_buff duration=8)
Define(dire_frenzy 217200)
	SpellInfo(dire_frenzy cd=15 focus=-25)
	SpellAddBuff(dire_frenzy dire_frenzy_buff=1)
Define(dire_frenzy_buff 217200)
	SpellInfo(dire_frenzy_buff duration=8)
Define(dire_frenzy_talent 5)
Define(dragonsfire_grenade 194855)
	SpellInfo(dragonsfire_grenade cd=30)
Define(explosive_shot 212431)
	SpellInfo(explosive_shot cd=6 focus=15)
	SpellRequire(explosive_shot cd 0=buff,lock_and_load_buff if_spell=black_arrow)
	SpellRequire(explosive_shot focus 0=buff,lock_and_load_buff if_spell=black_arrow)
	SpellAddBuff(explosive_shot lock_and_load_buff=-1 if_spell=black_arrow)
	SpellInfo(explosive_shot replace=explosive_shot_detonate if_spell=explosive_shot_detonate)
Define(explosive_shot_detonate 212679)
Define(explosive_trap 191433)
	SpellInfo(explosive_trap cd=30)
	SpellInfo(explosive_trap addcd=-20 if_spell=enhanced_traps)
Define(explosive_trap_debuff 13812)
	SpellInfo(explosive_trap_debuff duration=20 tick=2)
Define(flanking_strike 202800)
	SpellInfo(flanking_strike cd=6 focus=50)
Define(fury_of_the_eagle 203415)
	SpellInfo(fury_of_the_eagle cd=45)
Define(fury_of_the_eagle_debuff 203415) #TODO Does not seem to exist
Define(glyph_of_explosive_trap 119403)
Define(harpoon 190925)
	SpellInfo(harpoon cd=20)
Define(heart_of_the_phoenix 55709)
	SpellInfo(heart_of_the_phoenix cd=480)
Define(heart_of_the_phoenix_debuff 55711)
	SpellInfo(heart_of_the_phoenix_debuff duration=480)
Define(hunters_mark_debuff 185365)
Define(kill_command 34026)
	SpellInfo(kill_command cd=6 focus=40)
	SpellInfo(kill_command buff_focus_half=bestial_wrath_buff if_spell=bestial_wrath)
Define(killer_cobra_talent 20)
Define(lacerate 185855)
	SpellInfo(lacerate focus=35 cd=10)
	SpellAddTargetDebuff(lacerate lacerate_debuff=1)
Define(lacerate_debuff 185855)
Define(lone_wolf_talent 21)
Define(marked_shot 185901)
	SpellInfo(marked_shot focus=30)
	SpellAddBuff(marked_shot vulnerable=1)
	SpellRequire(marked_shot unusable 1=target_debuff,!hunters_mark_debuff)
Define(marking_targets_buff 223138)
	SpellInfo(marking_targets_buff duration=10)
Define(moknathal_tactics_buff 201081)
	SpellInfo(moknathal_tactics_buffs duration=8)
Define(mongoose_bite 190928)
	SpellInfo(mongoose_bite cd=12)
Define(mongoose_fury_buff 190931)
	SpellInfo(mongoose_fury_buff duration=12)
Define(multishot 2643)
	SpellInfo(multishot focus=40)
	SpellInfo(multishot buff_focus=bombardment_buff buff_focus_amount=-25 if_spell=bombardment)
	SpellInfo(multishot buff_focus=thrill_of_the_hunt_buff buff_focus_amount=-20 if_spell=thrill_of_the_hunt)
	SpellInfo(multishot buff_focus_half=bestial_wrath_buff if_spell=bestial_wrath)
	SpellAddBuff(multishot thrill_of_the_hunt_buff=-1 if_spell=thrill_of_the_hunt)
	SpellAddBuff(multishot focus_fire_buff=extend,1 itemset=T18 itemcount=2 specialization=beast_mastery)
	SpellAddTargetDebuff(multishot serpent_sting_debuff=1 if_spell=serpent_sting)
Define(patient_sniper_talent 16)
Define(pet_beast_cleave_buff 115939)
Define(piercing_shot 198670)
	SpellInfo(piercing_shot cd=30 focus=20)
Define(raptor_strike 186270)
	SpellInfo(raptor_strike focus=25)
	SpellAddTargetDebuff(raptor_strike serpent_sting_debuff=1 talent=serpent_sting_talent)
Define(revive_pet 982)
	SpellInfo(revive_pet focus=35)
	SpellInfo(revive_pet buff_focus_half=bestial_wrath_buff if_spell=bestial_wrath)
Define(sentinel 206817)
	SpellInfo(sentinel cd=30)
Define(serpent_sting_debuff 87935)
Define(serpent_sting_talent 18)
Define(sidewinders 214579)
	SpellInfo(sidewinders focus=-50 cd=12)
Define(sidewinders_talent 19)
Define(snake_hunter 201078)
	SpellInfo(snake_hunter cd=90)
	#TODO Add 3 charges of mongoose_bite
Define(spitting_cobra 194407)
	SpellInfo(spitting_cobra cd=60)
	SpellAddBuff(spitting_cobra spitting_cobra_buff)
Define(spitting_cobra_buff 194407)
	SpellInfo(spitting_cobra_buff duration=30)
Define(stampede 201430)
	SpellInfo(stampede cd=300)
	SpellInfo(stampede buff_cdr=cooldown_reduction_agility_buff)
Define(stampede_talent 15)
Define(steady_focus_buff 193534)
Define(steady_focus_talent 2)
Define(steel_trap 162488)
	SpellInfo(steel_trap cd=60)
Define(throwing_axes 200163)
	SpellInfo(throwing_axes focus=15 cd=15)
Define(titans_thunder 207068)
	SpellInfo(titans_thunder cd=60)
Define(titans_thunder_tick 207097)
Define(trap_launcher 77769)
	SpellInfo(trap_launcher cd=1.5)
Define(true_aim_debuff 199803)
Define(true_aim_talent 6)
Define(trueshot 193526)
	SpellInfo(trueshot cd=180)
	SpellAddBuff(trueshot trueshot_buff=1)
Define(trueshot_buff 193526)
	SpellInfo(trueshot_buff duration=15)
Define(volley 194386)
	SpellInfo(volley cd=1.5)
	SpellAddBuff(volley volley_buff=1)
Define(volley_buff 194386)
Define(vulnerable 187131)
	SpellInfo(vulnerable duration=30)
Define(vulnerability_debuff 187131)
	SpellInfo(vulnerability_debuff duration=30)
Define(way_of_the_moknathal_talent 3)
Define(windburst 204147)
	SpellInfo(windburst focus=20 cd=20)
]]
	OvaleScripts:RegisterScript("HUNTER", nil, name, desc, code, "include")
end
