local _, Ovale = ...
local OvaleScripts = Ovale.OvaleScripts

do
	local name = "ovale_warlock_spells"
	local desc = "[5.2] Ovale: Warlock spells"
	local code = [[
# Warlock spells and functions.

Define(agony 980)
	SpellInfo(agony duration=24 tick=2 haste=spell)
	SpellAddTargetDebuff(agony agony=1)
Define(backdraft 117896)
Define(chaos_bolt 116858)
	SpellInfo(chaos_bolt burningembers=10 tick=1 haste=spell)
	SpellAddTargetDebuff(chaos_bolt chaos_bolt=1)
Define(conflagrate 17962)
	SpellInfo(conflagrate duration=5)
	SpellAddBuff(conflagrate conflagrate=1)
Define(corruption 172)
	SpellAddTargetDebuff(corruption corruption_debuff=1)
Define(corruption_debuff 146739)
	SpellInfo(corruption_debuff duration=18 tick=2 haste=spell)
Define(curse_of_the_elements 1490)
	SpellInfo(curse_of_the_elements duration=300)
	SpellAddTargetDebuff(curse_of_the_elements aura_of_the_elements=1)
Define(dark_intent 109773)
	SpellInfo(dark_intent duration=3600)
	SpellAddBuff(dark_intent dark_intent=1)
Define(dark_soul_instability 113858)
	SpellInfo(dark_soul_instability duration=20 cd=120)
	SpellAddBuff(dark_soul_instability dark_soul_instability=1)
Define(dark_soul_knowledge 113861)
	SpellInfo(dark_soul_knowledge duration=20 cd=120)
	SpellAddBuff(dark_soul_knowledge dark_soul_knowledge=1)
Define(dark_soul_misery 113860)
	SpellInfo(dark_soul_misery duration=20 cd=120)
	SpellAddBuff(dark_soul_misery dark_soul_misery=1)
Define(doom 603)
	SpellInfo(doom duration=60 demonicfury=60 tick=15 haste=spell stance=1)
	SpellAddTargetDebuff(doom doom=1)
Define(drain_soul 1120)
	SpellInfo(drain_soul channel=6 haste=spell)
	SpellAddTargetDebuff(drain_soul drain_soul=1)
Define(fel_flame 77799)
Define(felstorm 89751)
	SpellInfo(felstorm duration=6 energy=60 cd=45)
	SpellAddBuff(felstorm felstorm=1)
Define(fire_and_brimstone 108683)
	SpellInfo(fire_and_brimstone burningembers=10 cd=1)
	SpellAddBuff(fire_and_brimstone fire_and_brimstone=1)
Define(grimoire_of_sacrifice 108503)
	SpellInfo(grimoire_of_sacrifice duration=3600 cd=30)
	SpellAddBuff(grimoire_of_sacrifice grimoire_of_sacrifice=1)
Define(grimoire_of_sacrifice_talent 15)
Define(grimoire_of_service_talent 14)
Define(hand_of_guldan 105174)
	SpellInfo(hand_of_guldan stance=0)
Define(haunt 48181)
	SpellInfo(haunt duration=8 tick=2 shards=1)
	SpellAddBuff(haunt haunt=1)
Define(havoc 80240)
	SpellInfo(havoc duration=15 cd=25)
	SpellAddBuff(havoc havoc=1)
Define(hellfire 1949)
	SpellInfo(hellfire channel=14 haste=spell)
	SpellAddTargetDebuff(hellfire hellfire=1)
Define(immolate 348)
	SpellInfo(immolate duration=15 tick=3 haste=spell)
	SpellAddTargetDebuff(immolate immolate=1)
Define(immolate_aoe 108686)
	SpellInfo(immolate_aoe duration=15 tick=3 haste=spell)
SpellList(immolate_debuff immolate immolate_aoe)
Define(immolation_aura 104025)
	SpellInfo(immolation_aura duration=10 demonicfury=0 stance=1)
	SpellAddBuff(immolation_aura immolation_aura=1)
Define(incinerate 29722)
Define(life_tap 1454)
	SpellInfo(life_tap mana=-15)
	SpellAddBuff(life_tap life_tap=1)
Define(malefic_grasp 103103)
	SpellInfo(malefic_grasp channel=4 haste=spell)
	SpellAddTargetDebuff(malefic_grasp malefic_grasp=1)
Define(melee 103988)
	SpellInfo(melee stance=1)
Define(metamorphosis 103958)
	SpellInfo(metamorphosis demonicfury=0 cd=10)
	SpellAddBuff(metamorphosis metamorphosis=1)
Define(molten_core 122355)
	SpellInfo(molten_core duration=30)
	SpellAddBuff(molten_core molten_core=1)
Define(rain_of_fire 5740)
	SpellInfo(rain_of_fire duration=6)
	SpellAddBuff(rain_of_fire rain_of_fire=1)
Define(rain_of_fire_aftermath 104232)
Define(seed_of_corruption 27243)
	SpellInfo(seed_of_corruption duration=18 tick=3 haste=spell)
	SpellAddTargetDebuff(seed_of_corruption seed_of_corruption=1)
Define(service_felguard 111898)
	SpellInfo(service_felguard cd=120)
Define(service_felhunter 111897)
	SpellInfo(service_felhunter cd=120)
Define(shadow_bolt 686)
	SpellInfo(shadow_bolt demonicfury=40 stance=0)
Define(shadowburn 17877)
	SpellInfo(shadowburn burningembers=10)
Define(shadowflame 47960)
	SpellInfo(shadowflame duration=6 tick=1 haste=spell)
	SpellAddTargetDebuff(shadowflame shadowflame=1)
Define(skull_banner 114207)
	SpellInfo(skull_banner duration=10 cd=180)
Define(soul_fire 6353)
	SpellAddBuff(soul_fire molten_core=-1)
Define(soul_swap 86121)
Define(soulburn 74434)
	SpellInfo(soulburn duration=30 shards=1 cd=1)
	SpellAddBuff(soulburn soulburn=1)
Define(soulburn_seed_of_corruption 86664)
Define(summon_doomguard 18540)
	SpellInfo(summon_doomguard cd=600)
Define(summon_felguard 30146)
	SpellInfo(summon_felguard demonicfury=0)
Define(summon_felhunter 691)
	SpellInfo(summon_felhunter demonicfury=0)
Define(summon_infernal 1122)
	SpellInfo(summon_infernal cd=600)
Define(touch_of_chaos 103964)
	SpellInfo(touch_of_chaos demonicfury=40 stance=1)
Define(unstable_affliction 30108)
	SpellInfo(unstable_affliction duration=14 tick=2 haste=spell)
	SpellAddTargetDebuff(unstable_affliction unstable_affliction=1)
Define(void_ray 115422)
	SpellInfo(void_ray demonicfury=40)
Define(wrathstorm 115831)
	SpellInfo(wrathstorm duration=6 energy=60 cd=45)
	SpellAddBuff(wrathstorm wrathstorm=1)
]]

	OvaleScripts:RegisterScript("WARLOCK", name, desc, code, "include")
end
