local OVALE, Ovale = ...
local OvaleScripts = Ovale.OvaleScripts

do
	local name = "nerien_priest_holy"
	local desc = "[6.2] Nerien: Holy"
	local code = [[
###
### Nerien's holy priest script.
###

Include(ovale_common)
Include(ovale_trinkets_mop)
Include(ovale_trinkets_wod)
Include(ovale_priest_spells)

AddCheckBox(opt_potion_mana ItemName(draenic_mana_potion) default specialization=holy)

AddFunction HolyUsePotionMana
{
	if CheckBoxOn(opt_potion_mana) Item(draenic_mana_potion usable=1)
}

AddFunction HolyAoeActions
{
	# Use PoM when Divine Insight procs.
	if BuffPresent(divine_insight_buff) Spell(prayer_of_mending)

	# Cast CoH and PoM on cooldown.
	Spell(circle_of_healing)
	Spell(prayer_of_mending)

	# AoE filler.
	Spell(prayer_of_healing)
}

AddFunction HolyCdActions
{
	if ManaPercent() <= 75 HolyUsePotionMana()
	if not Talent(mindbender_talent) and ManaPercent() < 80 Spell(shadowfiend)
	if ManaPercent() < 90 Spell(arcane_torrent_mana)
	Spell(lightwell)
	Spell(blood_fury_sp)
	Spell(berserking)
	if Talent(power_infusion_talent) Spell(power_infusion)
	Spell(divine_hymn)
}

AddFunction HolyMainActions
{
	# Maintain Renew on the tank.
	if BuffCountOnAny(renew_buff) == 0 Spell(renew)
	# Refresh Renew on the tank using Holy Word: Serenity.
	if Stance(priest_chakra_serenity) Spell(holy_word)

	# Use PoM when Divine Insight procs.
	if BuffPresent(divine_insight_buff) Spell(prayer_of_mending)
	# Use Flash Heal when Surge of Light procs.
	if BuffPresent(surge_of_light_buff) Spell(flash_heal)
	# Use PoM on cooldown.
	Spell(prayer_of_mending)
	# Use Heal at 2 stacks of Serendipity.
	if BuffStacks(serendipity_buff) >= 2 and ManaPercent() > 40 Spell(heal)

	# Single-target filler.
	if Stance(priest_chakra_sanctuary) Spell(renew)
	Spell(heal)
}

AddFunction HolyPrecombatMainActions
{
	if not BuffPresent(stamina_buff any=1) Spell(power_word_fortitude)
	# Default to Chakra: Sanctuary for raid healing.
	if not Stance(priest_chakra_sanctuary) and not Stance(priest_chakra_serenity) Spell(chakra_sanctuary)
	# PoM and Renew the tank.
	Spell(prayer_of_mending)
	if BuffCountOnAny(renew_buff) == 0 Spell(renew)
}

AddFunction HolyPrecombatCdActions
{
	unless not BuffPresent(stamina_buff any=1) and Spell(power_word_fortitude)
		or not Stance(priest_chakra_sanctuary) and not Stance(priest_chakra_serenity) and Spell(chakra_sanctuary)
	{
		Spell(lightwell)
	}
}

AddFunction HolyShortCdActions
{
	if Talent(power_word_solace_talent) Spell(power_word_solace)
	if Talent(mindbender_talent) and ManaPercent() < 80 Spell(mindbender)
	if Talent(halo_talent) Spell(halo_heal)
	if Talent(divine_star_talent) Spell(divine_star_heal)
	if Talent(cascade_talent) Spell(cascade_heal)
	if Stance(priest_chakra_sanctuary) Spell(holy_word)
}

### Holy icons.

AddCheckBox(opt_priest_holy_aoe L(AOE) default specialization=holy)

AddIcon checkbox=opt_priest_holy_aoe help=shortcd specialization=holy
{
	HolyShortCdActions()
}

AddIcon help=main specialization=holy
{
	if not InCombat() HolyPrecombatMainActions()
	HolyMainActions()
}

AddIcon checkbox=opt_priest_holy_aoe help=aoe specialization=holy
{
	if not InCombat() HolyPrecombatMainActions()
	HolyAoeActions()
}

AddIcon help=cd specialization=holy
{
	if not InCombat() HolyPrecombatCdActions()
	HolyCdActions()
}
]]
	OvaleScripts:RegisterScript("PRIEST", "holy", name, desc, code, "script")
end

-- THE REST OF THIS FILE IS AUTOMATICALLY GENERATED.
-- ANY CHANGES MADE BELOW THIS POINT WILL BE LOST.

do
	local name = "simulationcraft_priest_shadow_legion"
	local desc = "[7.0] SimulationCraft: Priest_Shadow_legion"
	local code = [[
# Based on SimulationCraft profile "Priest_Shadow_legion".
#	class=priest
#	spec=shadow

Include(ovale_common)
Include(ovale_trinkets_mop)
Include(ovale_trinkets_wod)
Include(ovale_priest_spells)
### Shadow icons.

AddCheckBox(opt_priest_shadow_aoe L(AOE) default specialization=shadow)
]]
	OvaleScripts:RegisterScript("PRIEST", "shadow", name, desc, code, "script")
end
