Ovale.defaut["HUNTER"] =
[[
Define(SERPENTSTING 1978)
Define(ARCANESHOT 3044)
Define(AIMEDSHOT 19434)
Define(MULTISHOT 2643)
Define(STEADYSHOT 56641)
Define(EXPLOSIVESHOT 53301)
Define(KILLSHOT 53351)
Define(RAPIDFIRE 3045)
Define(KILLCOMMAND 34026)
Define(BESTIALWRATH 19574)
Define(HUNTERSMARK 53338)
Define(BLACKARROW 3674)
Define(LOCKANDLOAD 56453)
Define(TALENTEXPLOSIVESHOT 2145)
Define(CALLOFTHEWILD 53434)
Define(CHIMERASHOT 53209)
Define(READINESS 23989)

SpellAddTargetDebuff(EXPLOSIVESHOT EXPLOSIVESHOT=2)
SpellInfo(EXPLOSIVESHOT cd=6)
SpellAddTargetDebuff(SERPENTSTING SERPENTSTING=15)
SpellAddTargetDebuff(BLACKARROW BLACKARROW=15)
SpellInfo(BLACKARROW cd=26)
SpellInfo(KILLSHOT cd=15)
SpellInfo(AIMEDSHOT cd=10)
SpellInfo(CHIMERASHOT cd=10)
SpellInfo(RAPIDFIRE cd=300)
SpellInfo(KILLCOMMAND cd=60)
SpellInfo(BESTIALWRATH cd=120)
SpellInfo(ARCANESHOT cd=6)
SpellAddTargetDebuff(HUNTERSMARK HUNTERSMARK=300)

AddCheckBox(multi SpellName(MULTISHOT))
ScoreSpells(HUNTERSMARK BLACKARROW SERPENTSTING CHIMERASHOT AIMEDSHOT MULTISHOT ARCANESHOT KILLSHOT STEADYSHOT)

AddIcon help=main
{
	if TargetDebuffExpires(HUNTERSMARK 0) and TargetDeadIn(more 8) Spell(HUNTERSMARK)
	if TargetDebuffExpires(BLACKARROW 0 mine=1) Spell(BLACKARROW)
	if TargetDebuffExpires(SERPENTSTING 0 mine=1) and TargetDeadIn(more 8) Spell(SERPENTSTING)
	if TargetDebuffExpires(EXPLOSIVESHOT 0 mine=1) Spell(EXPLOSIVESHOT)
	if TargetDebuffPresent(SERPENTSTING) Spell(CHIMERASHOT)
	Spell(AIMEDSHOT)
	if CheckBoxOn(multi) Spell(MULTISHOT)
	unless TalentPoints(TALENTEXPLOSIVESHOT more 0) Spell(ARCANESHOT)
	if TargetLifePercent(less 20) Spell(KILLSHOT)
	if TargetDebuffExpires(HUNTERSMARK 2) Spell(HUNTERSMARK nored=1)
	unless 1.5s before Spell(EXPLOSIVESHOT) Spell(STEADYSHOT)
}

AddIcon help=cd
{
	Spell(BESTIALWRATH usable=1)
	Spell(KILLCOMMAND usable=1)
    Item(Trinket0Slot usable=1)
	Item(Trinket1Slot usable=1)
	Spell(CALLOFTHEWILD usable=1)
	Spell(RAPIDFIRE)
	Spell(READINESS)
}
]]
